<?php

/**
 * @file
 * Module file for google_books.
 *
 * @see \Drupal\google_books\Plugin\Filter\google_books.
 */

/**
 * Implements hook_theme().
 */
function google_books_theme($existing, $type, $theme, $path) {
  return [
    'googlebooks_template' => [
      'variables' => [
        'title_link' => NULL,
        'title_anchor' => NULL,
        'worldcat_link' => NULL,
        'librarything_link' => NULL,
        'openlibrary_link' => NULL,
        'image' => NULL,
        'page_curl' => NULL,
        'reader' => NULL,
        'bib_fields' => NULL,
        'image_height' => NULL,
        'image_width' => NULL,
        'reader_height' => NULL,
        'reader_width' => NULL,
        'api_key' => NULL,
        'info_link' => NULL,
        'isbn' => NULL,
        'prevent_duplicate_values' => NULL
      ],
    ],
  ];
}
