<?php
/**
 * Googlebook Filter Module
 *
 *    for Drupal 7.0
 *
 * Copyright 2011 Darrell Ulm.
 * 
 * Based initialy on the BookPost module for Drupal 6 by Aaron Rubinstein,
 *   and partially based on the the OpenLibrary API for Drupal 6
 *
 * The googlebook module is a filter module 
 * that allows a user to insert rich Google Book
 * data into nodes via filters.
 *
 * The fields can be selected to be displayed globally. 
 *
 * See the INSTALL.TXT file for specific information.
 *
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */


/**
 * Function: filter_googlebook_tips
 *
 * The filter tips hook for the googlebook filter module
 *
 */
function filter_googlebook_tips( $filter, $format, $long = FALSE ) {
  if ($long) {
    return t('Put a Google Book search term between double brackets like this:
        {{The Hobbit}} or {{isbn:9780618154012}} or {{Rucker+Software}}
        and this will filter the input to replace with Google Book data
        and images from http://books.google.com');
  }
}


/**
 * Implements googlebook_filter_info()
 *
 * Filter info hook for googlebook filter
 * 
*/
function googlebook_filter_info() {
    $filters['googlebook'] = array(
        'title' => t('Google Book'),
        'description' => t('Insert Book Information from Google Books'),
        'process callback' => 'googlebook_filter_process',
        'settings callback' => 'googlebook_filter_settings',
        'default settings' => array(
            'worldcat' => 1,
            'openlibrary' =>  1,
            'librarything' => 1,
            'bib_fields' => bib_field_array()
        ),
    'tips callback' => 'filter_googlebook_tips',
    );
    return $filters;
}


/**
 * Implements googlebook_filter_settings
 *
 * The filter form hook for the googlebook filter
 * 
*/
function googlebook_filter_settings($form, &$form_state, $filter, $format, $defaults, $filters) {
      $settings['googlebook'] = array(
        '#type' => 'fieldset',
        '#title' => t('Google Book Filter'),
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
      );
      $settings['bib_fields'] = array(
      '#type' => 'select',
      '#multiple' => TRUE,
      '#title' => 'Google Book Data Fields to Use',
      '#required' => TRUE,
      '#options' => bib_field_array(),
      '#default_value' => isset($filter->settings['bib_fields']) ? $filter->settings['bib_fields'] : bib_field_array()
      );
      $settings['worldcat'] = array(
        '#type' => 'checkbox',
        '#title' => t('Link to WorldCat'),
        '#default_value' => isset($filter->settings['worldcat']) ? $filter->settings['worldcat'] : $defaults['worldcat'],
      );
      $settings['librarything'] = array(
        '#type' => 'checkbox',
        '#title' => t('Link to LibraryThing'),
        '#default_value' => isset($filter->settings['librarything']) ? $filter->settings['librarything'] : $defaults['librarything'],
      );
      $settings['openlibrary'] = array(
        '#type' => 'checkbox',
        '#title' => t('Link to Open Library'),
        '#default_value' => isset($filter->settings['openlibrary']) ? $filter->settings['openlibrary'] : $defaults['openlibrary'],
      );
      return $settings;
}


/**
 * Function: googlebook_filter_process()
 * 
 * Same code as used by BookPost Module
 *
 * Good for migration to googlebook for Drupal7
 * 
*/
function googlebook_filter_process($text, $filter, $format, $langcode, $cache, $cache_id) {
    preg_match_all('/{{(.*)}}/', $text, $match);
    $tag = $match[0];
    $book = array();
    $counter = 0;
    for ($i = 0; $i < count( $match[1] ); $i++) {
        $book[$counter] = retrieve_bookdata($match[1][$i], $filter->settings['worldcat'], $filter->settings['librarything']
            , $filter->settings['openlibrary'], $filter->settings['bib_fields'] );
        $counter++;
    }
    $text = str_replace($tag, $book, $text);
    return $text;
}


/**
 *  Function: retrieve_bookdata( $id, $worldcat_link, $librarything_link, $openlibrary_link, $bib_field_select )
 *
 *  Gets the book data from Google Books / other sites and then displays it.
 *  $id is a valid Google Book query
 *
 *  This is the main filter processing function that does the work.
 *
 *  $id : The full string pulled from inside the {{$id}} filter
 *  $worldcat_link : True if setting for Worldcat link on
 *  $librarything_link : True if setting for Library Thing link on
 *  $openlibrary_link : True if setting for openlibrary is on
 *  $bib_field_select : This is the array of True/False for the multi-field
 *     data select
 * 
 */
function retrieve_bookdata( $id, $worldcat_link, $librarything_link, $openlibrary_link, $bib_field_select ) {

    // Get all the Google Book permissible book data fieds
    $bib_fields = bib_field_array();

    // Clear some variables so we don't need to do it later
    $html_bookdata = "";
    $html_text = "";
    $html_fields = "";
    $worldcat = "";
    $librarything = "";
    $openlibrary = "";
    $extra_links = "";

    // This function pulls 
    $bib = get_googlebook_data( $id );
    
    // If the data is sound then continue 
    if ( $bib != FALSE ) {

        // Pull an ISBN if we have it, prefer the last 
        // which should be an ISBN 13 although may be something else :)
        $identifier_list = explode("|", $bib['identifier'] );
        $num_of_identifiers = count($identifier_list);
        $isbn = trim( $identifier_list[ $num_of_identifiers - 1 ] );
        $isbn = is_numeric( $isbn ) ? $isbn : "";

        // Get the book links if any are found. None are checked for ISBN validity.
        if ( ! empty( $isbn ) ) {
            if ($worldcat_link) {
                  $worldcat = '<a href="http://worldcat.org/isbn/' . $isbn . '" rel="nofollow" target="_blank">WorldCat</a><br />';
            }
            if ($librarything_link) {
                  $librarything = '<a href="http://librarything.com/isbn/' . $isbn . '" rel="nofollow" target="_blank">LibraryThing</a><br />';
            }
            if ($openlibrary_link) {
                  $openlibrary = '<a href="http://openlibrary.org/isbn/' . $isbn . '" rel="nofollow" target="_blank">Open Library</a><br />';
            }
            if ( strlen( $worldcat . $librarything . $openlibrary ) > 0 ) {
                $extra_links = "Link to:<br />";
            }
        }

        // Build up the HTML output for all the selected fields
        $html_fields .= "<ul>";
        foreach ( $bib_field_select as $i => $k ) {
            $field = $bib_fields[ $i ];
            $field_val = "";
            if ( isset( $bib [ $field ] ) ) {
                $field_val = $bib [ $field ];
            }
            if ( ! empty( $field_val ) ) {
                $html_fields .= "<li class='googlebook_" . $field . "'><span class='googlebook_name'>" . ucfirst( preg_replace('/[A-Z]/', ' $0', str_replace('_', ' ', $field) ) ) . ": </span><span class='googlebook_data'>" . make_html_link( $field_val ) . "</span></li>";
            }
        }
        $html_fields .= "</ul>";

        // Build the main title with a link
        $title = $bib['title'];
        $html_title = '<p>Title: <a href="' . $bib['infoLink'] . '" rel="nofollow" target="_blank"><i>' . $title . '</i></a></p>';

        // Build a coverimage
        if ( isset($bib['thumbnail']) ) {
            $html_coverimage = "<img src='" . $bib['thumbnail'] . "' alt='" . $title . "' />";
            $html_coverimage = "<a style='float:right' class='googlebook_image' href='" . $bib['infoLink'] . "' rel='nofollow' target='_blank'>" . $html_coverimage . "</a>";
        }

       // Create the final text
       $html_text .= $html_title;
       $html_text .= "<p class='googlebook_links'>" . $extra_links . $worldcat . $librarything . $openlibrary . "</p>";
       $html_text .= $html_fields;

       //div whole class for themeing
       $html_bookdata = '<div class="googlebooks" >' . $html_coverimage . $html_text . '<div style="clear:both;"></div></div>';
       }

  return $html_bookdata;
}


/**
 * Function: make_html_link( $address )
 *
 * If the bibli field looks like an address, make it a link
 *
 * $address : the biblio field, which might be an address
 *
*/
function make_html_link( $address ) {
    if ( strpos($address, "https://") !== FALSE || strpos($address, "http://") !== FALSE ) {
        return '<a href="' . $address . '" rel="nofollow" target="_blank"> link </a>';
    }
return $address;
}
